### ISSUE TITLE
ivy-posframe & ivy-hydra don't work with hydra-posframe

### ISSUE THREAD

**Issue by mclearc** [Ladicle/hydra-posframe#7]
When using ivy-posframe, if I call `hydra-ivy/body` it creates a new posframe in addition to the posframe for (e.g.) `counsel-M-x` and this seems to immediate problems of loss of focus. Is there a way to disable specific modes or commands for hydra-posframe?

**Comment by AloisJanicek** [comment]
This happens when both `hydra` and `ivy` uses same `posframe-poshandler-*` function. 
If you display `ivy` with `posframe-poshandler-frame-center` and hydras with `posframe-poshandler-frame-top-center`, you may fix it. [screenshot](https://i.imgur.com/SkqLKW7.png)

As `hydra-ivy/body` is probably only hydra with a chance of being displayed at the same time as `ivy`, you can wrap it with `let` block and set different `hydra-posframe-show-params` placing only this hydra at the top of the frame, out of the `ivy-posframe`'s way and finally (re)bind your code (function) to `C-o` in `ivy-minibuffer-map` instead of "vanilla" `hydra-ivy/body`.
If you don't keep your emacs' frame tall enough and even after this `ivy` posframe will overlap with `hydra` posframe on the top of the emacs frame, in the `let` I mentioned above customize `hydra-hint-display-type ` instead.

(SIDENOTE: `hydra-posframe` packages is kind of obsolete now - displaying `hydra`s in `posframe` is supported in `hydra` itself for some time now)
